ARG CADDY_VERSION=2.11.4
ARG WINDOWS_TAG=ltsc2022

FROM caddy:${CADDY_VERSION}-builder-windowsservercore-${WINDOWS_TAG} AS builder
ARG CADDY_VERSION

RUN xcaddy build v${CADDY_VERSION#v} \
      --with github.com/caddy-dns/desec \
      --output C:\caddy.exe

FROM caddy:${CADDY_VERSION}-windowsservercore-${WINDOWS_TAG} AS windowsservercore
COPY --from=builder C:\caddy.exe C:\caddy.exe

FROM caddy:${CADDY_VERSION}-nanoserver-${WINDOWS_TAG} AS nanoserver
COPY --from=builder C:\caddy.exe C:\caddy.exe
